import json
from database import SessionLocal, Scenario

SEED = [
    # ══════ EMAIL SCENARIOS ══════
    {"category":"email","type":"Phishing","difficulty":"Easy","sender_email":"support@amaz0n-security.com","sender_name":"Amazon Security","subject":"Your account has been locked!","body":"Dear Customer,\n\nWe detected suspicious activity on your Amazon account. Your account has been temporarily locked.\n\nPlease click the link below to verify your identity within 24 hours or your account will be permanently deleted.\n\nVerify Now: https://amaz0n-security.com/verify-account\n\nThank you,\nAmazon Customer Protection Team","correct_action":"opt3","options":json.dumps([{"id":"opt1","label":"Click verify link now","desc":"Restore account immediately"},{"id":"opt2","label":"Reply with my details","desc":"Confirm identity via email"},{"id":"opt3","label":"Open Amazon app directly","desc":"Check for real alerts there"},{"id":"opt4","label":"Forward link to friends","desc":"Warn them to check"}]),"red_flags":json.dumps(["Fake domain — 'amaz0n' uses zero instead of 'o'","24-hour urgency deadline","Generic 'Dear Customer' greeting","Suspicious non-Amazon link"])},
    {"category":"email","type":"BEC","difficulty":"Medium","sender_email":"ceo.james@company-mail.net","sender_name":"James Wright (CEO)","subject":"Urgent wire transfer needed","body":"Hi,\n\nI need you to process a wire transfer of $32,000 to a new supplier immediately. I'm traveling and can't do it myself.\n\nWire to:\nBank: Pacific Trust\nAccount: 7739201854\n\nPlease handle this right away and don't mention it to others — the deal is confidential.\n\nThanks,\nJames\n\nSent from my iPhone","correct_action":"opt4","options":json.dumps([{"id":"opt1","label":"Process transfer immediately","desc":"Help the CEO with urgent deal"},{"id":"opt2","label":"Reply confirming receipt","desc":"Acknowledge and process soon"},{"id":"opt3","label":"Forward to finance team","desc":"Let them handle the details"},{"id":"opt4","label":"Call CEO on known number","desc":"Verify request via phone first"}]),"red_flags":json.dumps(["CEO requesting money via email","Asks for secrecy","Creates urgency pressure","No purchase order referenced"])},
    {"category":"email","type":"Spear Phishing","difficulty":"Hard","sender_email":"hr-benefits@company-portal.com","sender_name":"HR Benefits Portal","subject":"Update your direct deposit info","body":"Hello,\n\nAs part of our annual payroll system upgrade, all employees must re-verify their direct deposit information by end of business Friday.\n\nPlease log in to the employee portal below and confirm your banking details:\n\nhttps://company-portal.com/payroll/verify\n\nEmployees who do not update may experience paycheck delays.\n\nBest regards,\nHuman Resources Department","correct_action":"opt3","options":json.dumps([{"id":"opt1","label":"Log in and update info","desc":"Ensure paycheck isn't delayed"},{"id":"opt2","label":"Reply to HR asking details","desc":"Get more context first"},{"id":"opt3","label":"Visit HR office in person","desc":"Ask HR directly about this"},{"id":"opt4","label":"Forward to IT to check","desc":"Let IT decide if legitimate"}]),"red_flags":json.dumps(["External domain pretending to be internal HR","Requests banking info via email link","Deadline pressure","Threatens paycheck delay"])},

    # ══════ FAKE WEBSITE SCENARIOS ══════
    {"category":"website","type":"Fake Login","difficulty":"Easy","subject":"Fake Amazon Login Page","body":"You receive an email saying your Amazon order has a delivery issue. You click the link and land on what looks like Amazon's login page.\n\nThe page has the Amazon logo at the top, a sign-in form asking for your email and password, and a 'Sign In' button. Below it says 'New to Amazon? Create your account.'\n\nHowever, looking more closely:\n- The URL bar shows: http://amaz0n-login.com/signin\n- There is no padlock icon (no SSL)\n- The logo looks slightly pixelated\n- The footer says '© 2021 Amazon' (outdated year)\n- The 'Create account' link doesn't work","correct_action":"opt2","options":json.dumps([{"id":"opt1","label":"Enter my Amazon password","desc":"Sign in to check my order"},{"id":"opt2","label":"Close tab, open amazon.com","desc":"Go to real Amazon directly"},{"id":"opt3","label":"Try the Create Account link","desc":"Test if the site works"},{"id":"opt4","label":"Enter a fake password to test","desc":"See what happens with wrong info"}]),"red_flags":json.dumps(["URL is 'amaz0n-login.com' not 'amazon.com'","No HTTPS/SSL padlock icon","Pixelated logo — copied, not official","Outdated copyright year 2021"]),"extra_data":json.dumps({"fake_url":"http://amaz0n-login.com/signin","real_url":"https://www.amazon.com/signin","ssl_valid":False,"domain_age":"3 days","visual_differences":["Pixelated logo","No SSL padlock","Outdated footer year","Dead links"]})},
    {"category":"website","type":"Clone Site","difficulty":"Medium","subject":"Fake Microsoft 365 Login","body":"Your IT department sent an email about a mandatory password reset. The link takes you to a Microsoft 365 login page.\n\nThe page looks professional with the Microsoft logo, a clean sign-in form, and the text 'Sign in to your account.' The design matches Microsoft's current style.\n\nBut examining closely:\n- URL: https://microsoft365-login.net/oauth\n- SSL certificate shows valid (green padlock)\n- The page loads slightly slower than usual\n- After entering email, it asks for both password AND phone number on the same page (real Microsoft asks for these separately)\n- The 'Can't access your account?' link goes to the same page","correct_action":"opt3","options":json.dumps([{"id":"opt1","label":"Enter my work credentials","desc":"Complete the password reset"},{"id":"opt2","label":"Enter email only first","desc":"See what happens next"},{"id":"opt3","label":"Go to office.com directly","desc":"Reset from official portal"},{"id":"opt4","label":"Reply to IT email asking","desc":"Confirm via email"}]),"red_flags":json.dumps(["Domain 'microsoft365-login.net' is not microsoft.com","Asks for password AND phone together — unusual","Help links loop back to same page","Slower loading — hosted on cheap server"]),"extra_data":json.dumps({"fake_url":"https://microsoft365-login.net/oauth","real_url":"https://login.microsoftonline.com","ssl_valid":True,"domain_age":"12 days","visual_differences":["Password and phone on same page","Help links don't work","Slightly slow loading","Missing language selector"]})},
    {"category":"website","type":"Banking Clone","difficulty":"Hard","subject":"Fake Chase Bank Portal","body":"You receive a text about unusual activity on your Chase account. The link opens what appears to be Chase's online banking portal.\n\nThe page is nearly identical to Chase's real site: correct blue color scheme, the Chase logo, navigation menu with 'Personal | Business | Commercial', and a login form with 'Username' and 'Password' fields.\n\nVery subtle differences:\n- URL: https://chase-secure-banking.com/login (not chase.com)\n- The 'Forgot Password' link works but goes to a different-looking page\n- In the footer, 'JPMorgan Chase & Co.' link doesn't navigate anywhere\n- The 'Enroll' button for new users leads to an error page\n- Browser shows a valid SSL certificate but issued to 'Chase Banking LLC' not 'JPMorgan Chase'","correct_action":"opt1","options":json.dumps([{"id":"opt1","label":"Call number on card back","desc":"Verify with Chase directly"},{"id":"opt2","label":"Enter username only","desc":"See if it recognizes me"},{"id":"opt3","label":"Check the SSL certificate","desc":"Verify who owns the cert"},{"id":"opt4","label":"Use the Forgot Password link","desc":"Test if the site is real"}]),"red_flags":json.dumps(["Domain 'chase-secure-banking.com' not 'chase.com'","SSL cert issued to wrong entity","Footer links non-functional","Enroll button leads to error page"]),"extra_data":json.dumps({"fake_url":"https://chase-secure-banking.com/login","real_url":"https://www.chase.com","ssl_valid":True,"domain_age":"8 days","visual_differences":["Wrong SSL certificate issuer","Dead footer links","Enroll button broken","Subtle font mismatch"]})},

    # ══════ QR CODE SCENARIOS ══════
    {"category":"qr","type":"QR Phishing","difficulty":"Easy","subject":"Free WiFi QR at coffee shop","body":"You're at a coffee shop and notice a QR code taped to the wall next to a handwritten sign: 'FREE HIGH-SPEED WIFI - Scan to Connect!'\n\nThe QR code is printed on a plain white sticker that looks like it was placed recently — the edges are slightly peeling. The coffee shop's regular WiFi name is printed on the official menu as 'CafeConnect_5G'.\n\nWhen you scan the QR code with your phone camera, the preview shows it leads to: http://free-wifi-login.xyz/connect\n\nThe page asks you to enter your email and create a password to 'activate free premium WiFi access.'","correct_action":"opt3","options":json.dumps([{"id":"opt1","label":"Enter email and connect","desc":"Get free fast WiFi"},{"id":"opt2","label":"Use the password from menu","desc":"Connect to official WiFi"},{"id":"opt3","label":"Ask staff about the QR","desc":"Verify if it's from the shop"},{"id":"opt4","label":"Scan and just browse first","desc":"See if WiFi works before login"}]),"red_flags":json.dumps(["Sticker looks recently added — not official","URL is .xyz domain, not the shop's","Asks for email and password creation","Official WiFi is already listed on menu"]),"extra_data":json.dumps({"location":"Coffee shop wall","claimed_purpose":"Free WiFi access","actual_destination":"http://free-wifi-login.xyz/connect","qr_placement":"Sticker taped next to handwritten sign"})},
    {"category":"qr","type":"Payment QR Swap","difficulty":"Medium","subject":"Restaurant payment QR code","body":"You just finished dinner at a restaurant. The waiter brings the bill with a QR code at the bottom: 'Scan to pay with any UPI/payment app.'\n\nYou notice the QR code sticker looks like it was placed OVER another QR code underneath — the edges of the top sticker are slightly raised. The restaurant name on the bill says 'Bella Italia' but when you scan the QR code, your payment app shows the recipient as 'FOODY_SERVICES_2024' instead of 'Bella Italia Restaurant.'\n\nThe amount matches your bill: $47.85. The payment page looks normal otherwise.","correct_action":"opt4","options":json.dumps([{"id":"opt1","label":"Pay — amount matches","desc":"Bill amount is correct"},{"id":"opt2","label":"Add a tip and pay","desc":"Complete the payment"},{"id":"opt3","label":"Ask for cash payment instead","desc":"Avoid QR altogether"},{"id":"opt4","label":"Show waiter the mismatch","desc":"Alert staff about wrong name"}]),"red_flags":json.dumps(["QR sticker placed over another QR — tampered","Recipient name doesn't match restaurant","'FOODY_SERVICES_2024' is not Bella Italia","Physical QR swap is a common attack method"]),"extra_data":json.dumps({"location":"Restaurant bill","claimed_purpose":"Pay restaurant bill","actual_destination":"Payment to FOODY_SERVICES_2024","qr_placement":"Sticker placed over original QR code"})},

    # ══════ VISHING SCENARIOS ══════
    {"category":"vishing","type":"Bank Call Scam","difficulty":"Easy","subject":"Fake bank fraud department call","body":"Caller: Hello, this is the fraud detection department from your bank. Am I speaking with the account holder?\n\nYou: Yes, who is this?\n\nCaller: Ma'am/Sir, we've detected three unauthorized transactions on your debit card totaling $2,847. We need to verify your identity RIGHT NOW to block further charges.\n\nYou: What transactions?\n\nCaller: I cannot share details over the phone for security reasons until you verify your identity. Please confirm your full card number, the CVV on the back, and your date of birth.\n\nYou: That seems like a lot of information...\n\nCaller: I understand your concern, but if we don't act in the next 5 minutes, the thieves will drain your entire account. We're trying to PROTECT you. Every second counts. What is your card number?","correct_action":"opt2","options":json.dumps([{"id":"opt1","label":"Give card number to help","desc":"They need it to block fraud"},{"id":"opt2","label":"Hang up, call bank directly","desc":"Use number on card back"},{"id":"opt3","label":"Give only date of birth","desc":"Share minimal info"},{"id":"opt4","label":"Ask for their badge number","desc":"Verify they're real"}]),"red_flags":json.dumps(["Real banks never ask for full card number over phone","Extreme urgency — '5 minutes' pressure","Refuses to share transaction details first","Asks for CVV — banks already have this"]),"extra_data":json.dumps({"caller_id":"+1-800-555-0147 (Bank Fraud Dept)","claimed_organization":"Your Bank Fraud Department","tactics_used":["urgency","fear","authority"],"info_requested":["card number","CVV","date of birth"]})},
    {"category":"vishing","type":"Tech Support Scam","difficulty":"Medium","subject":"Microsoft tech support call","body":"Caller: Good afternoon. I'm calling from Microsoft Windows Technical Support. My name is Kevin. We've received automated alerts from your computer showing it has been infected with a dangerous virus. Your Windows license may also be at risk.\n\nYou: How did you get my number?\n\nCaller: Your computer sends diagnostic data to Microsoft servers. Our system flagged your IP address for malicious activity. I can help you fix this today at no charge. First, I'll need you to open your computer.\n\nYou: Okay, I'm at my computer.\n\nCaller: Great. Press the Windows key and R at the same time. Now type 'eventvwr' and press Enter. Do you see some warnings and errors listed there?\n\nYou: Yes, there are some yellow and red icons.\n\nCaller: Those are the infections I was telling you about. Very serious. I need you to now go to this website: support-fix-now.com and download our remote access tool so I can clean your system.\n\nYou: A remote access tool?","correct_action":"opt3","options":json.dumps([{"id":"opt1","label":"Download the tool to fix","desc":"Let them clean the virus"},{"id":"opt2","label":"Ask for employee ID first","desc":"Verify their identity"},{"id":"opt3","label":"Hang up immediately","desc":"Microsoft doesn't call you"},{"id":"opt4","label":"Check Event Viewer myself","desc":"Verify the warnings are real"}]),"red_flags":json.dumps(["Microsoft never makes unsolicited support calls","Event Viewer ALWAYS has warnings — they're normal","Asking to install remote access tool — gives them control","'support-fix-now.com' is not a Microsoft domain"]),"extra_data":json.dumps({"caller_id":"+1-800-555-0199 (Microsoft Support)","claimed_organization":"Microsoft Windows Technical Support","tactics_used":["authority","technical jargon","fear"],"info_requested":["remote access","computer control"]})},

    # ══════ USB DROP SCENARIOS ══════
    {"category":"usb","type":"Curiosity Bait","difficulty":"Easy","subject":"USB labeled 'Employee Salaries 2024' in parking lot","body":"You arrive at work and find a USB flash drive on the ground in the company parking lot. It's a cheap-looking black USB with a handwritten sticky label that reads:\n\n'CONFIDENTIAL - Employee Salaries Q4 2024'\n\nThe USB looks relatively new and clean. No one else seems to have noticed it. You're curious about whether your salary matches your colleagues'.\n\nIf you were to plug it into your work computer, your file explorer would show:\n- Salaries_Q4_2024.xlsx (2.3 MB)\n- Bonus_Structure_Confidential.pdf (890 KB)\n- HR_Notes_Performance_Reviews.docx (445 KB)\n\nHidden from view: an autorun.inf file and a malware executable that would install a keylogger capturing everything you type, including passwords and banking details.","correct_action":"opt3","options":json.dumps([{"id":"opt1","label":"Plug in to check contents","desc":"Satisfy my curiosity"},{"id":"opt2","label":"Plug into personal phone","desc":"Safer than work computer"},{"id":"opt3","label":"Turn it in to IT security","desc":"Let professionals handle it"},{"id":"opt4","label":"Throw it in the trash","desc":"Not worth the risk"}]),"red_flags":json.dumps(["'Confidential salary' label is designed to trigger curiosity","USB found in public area — classic drop attack","Handwritten label — not official IT equipment","Hidden autorun malware installs keylogger"]),"extra_data":json.dumps({"found_location":"Company parking lot","usb_label":"CONFIDENTIAL - Employee Salaries Q4 2024","usb_appearance":"Cheap black USB with handwritten sticky label","files_if_opened":["Salaries_Q4_2024.xlsx","Bonus_Structure_Confidential.pdf","HR_Notes_Performance_Reviews.docx"],"hidden_payload":"Autorun malware installing keylogger"})},
    {"category":"usb","type":"Branded USB","difficulty":"Hard","subject":"Company-branded USB in conference room","body":"After a client meeting in your company's main conference room, you notice a USB flash drive left on the table. It's a sleek branded USB with your company's logo printed on it — the same type given out at last quarter's company town hall.\n\nA small label on the back reads: 'Q3 Board Presentation - Final v2'\n\nIt looks completely legitimate — same branding, same USB model your company uses for official presentations. You recall that the board presentation from last quarter was never shared with your department.\n\nIf plugged in, the USB shows:\n- Q3_Board_Presentation_Final.pptx (15.2 MB)\n- Financial_Summary_Q3.xlsx (3.1 MB)\n- Strategic_Roadmap_2025.pdf (5.4 MB)\n\nThe files appear to open normally, but a hidden script silently installs a backdoor that gives an attacker persistent access to your network.","correct_action":"opt2","options":json.dumps([{"id":"opt1","label":"Open it — it's company branded","desc":"Looks official and legitimate"},{"id":"opt2","label":"Give to IT for scanning first","desc":"Let them verify it's safe"},{"id":"opt3","label":"Ask colleagues who left it","desc":"Find the owner"},{"id":"opt4","label":"Open on a personal laptop","desc":"Keep work computer safe"}]),"red_flags":json.dumps(["Attackers can easily clone company-branded USBs","Left after client meeting — outsiders had access","Board presentations are typically shared via email/cloud, not USB","Hidden backdoor installs even when files appear normal"]),"extra_data":json.dumps({"found_location":"Company conference room after client meeting","usb_label":"Q3 Board Presentation - Final v2","usb_appearance":"Sleek branded USB with company logo, identical to official ones","files_if_opened":["Q3_Board_Presentation_Final.pptx","Financial_Summary_Q3.xlsx","Strategic_Roadmap_2025.pdf"],"hidden_payload":"Silent backdoor script granting persistent network access"})},
]

def seed_database():
    db = SessionLocal()
    try:
        existing = db.query(Scenario).filter(Scenario.is_ai_generated == False).count()
        if existing < len(SEED):
            existing_subjects = set(s.subject for s in db.query(Scenario).filter(Scenario.is_ai_generated == False).all())
            added = 0
            for data in SEED:
                if data["subject"] not in existing_subjects:
                    scenario = Scenario(**data, is_ai_generated=False)
                    db.add(scenario)
                    added += 1
            db.commit()
            print(f"Seeded {added} new scenarios (total: {existing + added})")
        else:
            print(f"Database has {existing} static scenarios, skipping seed")
    finally:
        db.close()
